### ISSUE TITLE
Video's Intro Text

### ISSUE THREAD

**Issue by johnlonganecker** [starkandwayne/www-static#3]
http://www.starkandwayne.com/videos/

**Current Intro Text**

> Training videos we share amongst ourselves, with our customers and within our Cloud Foundry community.
> 
> If they are useful or have requests, please leave comments.

I think intro text is not necessary but if we want to have something perhaps we can change it to

> Have a comments, future video to request, or video to share? Let us know with a comment.

**Comment by drnic** [comment]
I don't yet have a way to change the title to say "Videos"; so yeah the first paragraph is stating what this page is about.

Also, there is a "story" or "reason" I'm communicating in the announcement blog post https://www.starkandwayne.com/blog/ghost/editor/179/:

> Our own needs were to create 100s of training videos for our Stark & Wayne staff and customers, and yet we quickly got excited about sharing them with everyone in the Cloud Foundry and/or Concourse ecosystems.

But, I'll keep thinking about it. 

I'll change the 2nd paragraph to your suggestion.

**Comment by johnlonganecker** [comment]
Sure makes sense. I think most the time when people visit a page with videos that don't really read much text they just want to get to the videos.

In the future it would be cool to have a more grid like layout with each row being a topic/tag

**Comment by drnic** [comment]
Yep, I just threw up the blog app as a v1 of /videos site. 

Priority is to get me to create lots of videos. We can follow up on a better v2 site if I get tricked into creating enough content to justify it :)

**Comment by johnlonganecker** [comment]
👍 just giving my 2 cents as I see it. Do what you want with the input 😄 

Content is always the hardest part!

**Comment by drnic** [comment]
If you have ideas/proposals for v2 layout/goals/etc I'd love them
My thinking is around the railscasts.com site features for their per-episode page.
And some linear episode by episode guide towards certain learning objectives.

On Fri, May 20, 2016 at 11:43 AM -0700, "John Longanecker" notifications@github.com wrote:

👍 just giving my 2 cents as I see it. Do what you want with the input 😄

**Comment by johnlonganecker** [comment]
I think linear layout makes more sense when you don't have as much content, but once you have more content a grid layout with less text makes more sense like youtube with rows for topics that have their own pages.

We can have that discussion I guess once we have more content 😄
